<a href="https://colab.research.google.com/github/godricgryffindoor502-del/reimagined-enigma/blob/main/Python%20Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [67]:
def quicksort(arr):
  if len(arr) <= 1:
    return arr
  pivot =arr[len(arr) // 2]
  left = [x for x in arr if x < pivot]
  middle=[x for x in arr if x == pivot]
  right = [x for x in arr if x > pivot]
  return quicksort(left) + middle + quicksort(right)
print(quicksort([1,5,2,5,3,90,2,44,7]))

[1, 2, 2, 3, 5, 5, 7, 44, 90]


In [68]:
x=3
print(type(x))
print(x)
print(x+5)
print(x-9)
print(x*34)
print(x**5)
x+=1
print(x)

<class 'int'>
3
8
-6
102
243
4


In [69]:
y=2.5
print(type(y))

<class 'float'>


In [70]:
t=True
f=False
print(type(t))
print(t and f)
print(t or f)
print(2 ^ 5)
print(t ^ f)
print(not f)
print(t==f)

<class 'bool'>
False
True
7
True
True
False


In [71]:
hello = 'hello'
world = "world"
print(hello)
print(len(hello))
hw=hello+' '+world
print(hw)
hw12 = '%s %s %d' % (hello,world,21)
print(hw12)

hello
5
hello world
hello world 21


In [72]:
print(hello.capitalize())
print(hello.upper())
print(hello.rjust(10))
print(hw12.ljust(30))
print(hw.center(20))
print(hw.replace('world','universe'))
print(' gbiu '.strip())

Hello
HELLO
     hello
hello world 21                
    hello world     
hello universe
gbiu


In [73]:
ls=[3,2,4,5,1,-10]
print(ls,ls[2])
print(ls[-1])
ls[0]="dhruv"
print(ls)
ls.append("bob")
print(ls)
last = ls.pop()
print(ls,last)

[3, 2, 4, 5, 1, -10] 4
-10
['dhruv', 2, 4, 5, 1, -10]
['dhruv', 2, 4, 5, 1, -10, 'bob']
['dhruv', 2, 4, 5, 1, -10] bob


In [74]:
nums = list(range(10,100,10))
print(nums)
nums2=list(range(7))
print(nums2)
print(nums[1:7])
print(nums[4:])
print(nums[:4])
print(nums[:])
print(nums[:-1])
nums2[1:3]=[20,25]
print(nums2)

[10, 20, 30, 40, 50, 60, 70, 80, 90]
[0, 1, 2, 3, 4, 5, 6]
[20, 30, 40, 50, 60, 70]
[50, 60, 70, 80, 90]
[10, 20, 30, 40]
[10, 20, 30, 40, 50, 60, 70, 80, 90]
[10, 20, 30, 40, 50, 60, 70, 80]
[0, 20, 25, 3, 4, 5, 6]


In [75]:
planets =["Mercury","Venus", "Earth", "Mars","Jupiter"]
for planet in planets:
  print(planet)

Mercury
Venus
Earth
Mars
Jupiter


In [76]:
for idx,planet in enumerate(planets):
  print('#%d: %s' % (idx+1,planet))

#1: Mercury
#2: Venus
#3: Earth
#4: Mars
#5: Jupiter


In [77]:
import math

In [78]:
nums = list(range(10,110,10))
pis=[]
for x in nums:
  pis.append(x*math.pi)
print(pis)

[31.41592653589793, 62.83185307179586, 94.24777960769379, 125.66370614359172, 157.07963267948966, 188.49555921538757, 219.9114857512855, 251.32741228718345, 282.7433388230814, 314.1592653589793]


In [79]:
nums= list(range(11))
cubes=[x ** 3 for x in nums]
print(nums)
print(cubes)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[0, 1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]


In [80]:
cubes_and_even=[x for x in cubes if x%2==0]
print(cubes_and_even)

[0, 8, 64, 216, 512, 1000]


In [81]:
keys = {'adam':'gilchrist','sachin':'tendulkar','planet':12}
print(keys['adam'])
print('alice' in keys)
keys['alice']='bob'
print('alice' in keys)
print(keys.get('sparrow',"No Sparrow here"))
print(keys.get('sachin',"No Sachin here"))
del keys['sachin']
print(keys.get('sachin',"No Sachin here"))
print(keys)

gilchrist
False
True
No Sparrow here
tendulkar
No Sachin here
{'adam': 'gilchrist', 'planet': 12, 'alice': 'bob'}


In [82]:
ages = {"adam":25,"alice":21,"bob":23}
print(ages)
for name in ages :
  print('%s has age %d years' % (name,ages[name]))

{'adam': 25, 'alice': 21, 'bob': 23}
adam has age 25 years
alice has age 21 years
bob has age 23 years


In [83]:
for name,age in ages.items():
  print('%s : %d years' % (name,age))

adam : 25 years
alice : 21 years
bob : 23 years


In [84]:
nums=list(range(11))
odd_to_square={x:x**2 if x%2==1 else x for x in nums}
print(odd_to_square)

{0: 0, 1: 1, 2: 2, 3: 9, 4: 4, 5: 25, 6: 6, 7: 49, 8: 8, 9: 81, 10: 10}


In [85]:
animals={'cat','dog','elephant','rodent','prairie dog'}
print('bull' in animals)
animals.add('bull')
print('bull' in animals)
animals.remove('bull')
print('bull' in animals)
print(len(animals))

False
True
False
5


In [86]:
for idx,animal in enumerate(animals):
  print('#%d : %s' % (idx+1,animal))

#1 : rodent
#2 : dog
#3 : prairie dog
#4 : cat
#5 : elephant


In [87]:
sqrts={math.sqrt(x) for x in range(21)}
for idx,num in enumerate(sqrts):
  print('#%d : %d--> %s' % (idx+1,idx,num))

#1 : 0--> 0.0
#2 : 1--> 1.0
#3 : 2--> 2.0
#4 : 3--> 1.7320508075688772
#5 : 4--> 1.4142135623730951
#6 : 5--> 2.23606797749979
#7 : 6--> 2.449489742783178
#8 : 7--> 2.6457513110645907
#9 : 8--> 2.8284271247461903
#10 : 9--> 3.0
#11 : 10--> 3.1622776601683795
#12 : 11--> 3.3166247903554
#13 : 12--> 3.4641016151377544
#14 : 13--> 4.0
#15 : 14--> 4.47213595499958
#16 : 15--> 3.7416573867739413
#17 : 16--> 3.872983346207417
#18 : 17--> 4.123105625617661
#19 : 18--> 4.242640687119285
#20 : 19--> 4.358898943540674
#21 : 20--> 3.605551275463989


In [88]:
d= { (x,x+1): x for x in range(10)}
print(d)
t=(1,2,3,4,54)
print(t)
# t[0]=44

{(0, 1): 0, (1, 2): 1, (2, 3): 2, (3, 4): 3, (4, 5): 4, (5, 6): 5, (6, 7): 6, (7, 8): 7, (8, 9): 8, (9, 10): 9}
(1, 2, 3, 4, 54)


In [89]:
def abs(x):
  if x>=0:
    return x
  else:
     return -x
for x in range(-10,11):
  print(abs(x))

10
9
8
7
6
5
4
3
2
1
0
1
2
3
4
5
6
7
8
9
10


In [91]:
def hello(name,loud=False):
  if loud:
    print("HELLO, %s!" % name.upper())
  else:
    print("Hello, %s!" % name.capitalize())
hello("bob")
hello("Alice",loud=True)

Hello, Bob!
HELLO, ALICE!


In [92]:
class Greeter:
  def __init__(self,name):
    self.name=name
  def greet(self,loud=False):
     if loud:
        print("HELLO, %s!" % self.name.upper())
     else:
        print("Hello, %s!" % self.name.capitalize())
g=Greeter('Dhruv')
g.greet()
g.greet(loud=True)



Hello, Dhruv!
HELLO, DHRUV!


In [97]:
import numpy as np
a = np.array([x for x in range(11)])
print(a, type(a))
print(a.shape)
b=np.array([[[i*j*k for i in range(10)] for j in range(7)] for k in range(4)])
print(b,type(b),b.shape)

[ 0  1  2  3  4  5  6  7  8  9 10] <class 'numpy.ndarray'>
(11,)
[[[  0   0   0   0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0   0   0   0]]

 [[  0   0   0   0   0   0   0   0   0   0]
  [  0   1   2   3   4   5   6   7   8   9]
  [  0   2   4   6   8  10  12  14  16  18]
  [  0   3   6   9  12  15  18  21  24  27]
  [  0   4   8  12  16  20  24  28  32  36]
  [  0   5  10  15  20  25  30  35  40  45]
  [  0   6  12  18  24  30  36  42  48  54]]

 [[  0   0   0   0   0   0   0   0   0   0]
  [  0   2   4   6   8  10  12  14  16  18]
  [  0   4   8  12  16  20  24  28  32  36]
  [  0   6  12  18  24  30  36  42  48  54]
  [  0   8  16  24  32  40  48  56  64  72]
  [  0  10  20  30  40  50  60  70  80  90]
  [  0  12  24  36  48  60  72  84  96 108]]

 [[  

In [98]:
c=np.array([[x*y for x in range(1,11)] for y in range(1,10)])
print(c)

[[ 1  2  3  4  5  6  7  8  9 10]
 [ 2  4  6  8 10 12 14 16 18 20]
 [ 3  6  9 12 15 18 21 24 27 30]
 [ 4  8 12 16 20 24 28 32 36 40]
 [ 5 10 15 20 25 30 35 40 45 50]
 [ 6 12 18 24 30 36 42 48 54 60]
 [ 7 14 21 28 35 42 49 56 63 70]
 [ 8 16 24 32 40 48 56 64 72 80]
 [ 9 18 27 36 45 54 63 72 81 90]]


In [99]:
print(c.shape)

(9, 10)


In [103]:
def make_nd_array(shape,func=lambda:1):
  if len(shape)==1:
    return [func() for _ in range(shape[0])]
  return [make_nd_array(shape[1:],func) for _ in range(shape[0])]



In [105]:
import random
arr=make_nd_array((2,3,4,5,6,7))
for i in arr:
  print(i)


[[[[[1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1]], [[1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1]], [[1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1]], [[1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1]], [[1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1]]], [[[1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1]], [[1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1]], [[1, 1, 1, 1, 1

In [108]:
arr2=make_nd_array((3,4,5),lambda:random.randint(1,10))
print(arr2)

[[[1, 7, 4, 4, 4], [10, 4, 4, 9, 3], [8, 5, 9, 6, 9], [7, 5, 9, 9, 5]], [[3, 8, 4, 3, 2], [2, 7, 5, 9, 9], [8, 7, 1, 5, 3], [6, 8, 7, 7, 5]], [[3, 6, 9, 3, 1], [6, 3, 1, 5, 6], [7, 4, 5, 9, 9], [10, 7, 9, 1, 4]]]


In [110]:
print(np.zeros((2,2,2)))

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [111]:
print(np.ones((10,10)))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [112]:
print(np.full((10,10,10),3))

[[[3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]]

 [[3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]]

 [[3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]]

 [[3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]]

 [[3 3 3 3 3 3 3 3 3 3]
  [3 3 3

In [114]:
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [119]:
print(np.random.exponential(1,10))

[1.77802916 2.46075116 0.74191113 1.49713279 1.21674835 2.33059479
 2.65768882 0.257797   0.6358716  0.89584717]


In [120]:
print(np.random.random((2,3,4)))

[[[0.8290859  0.65324371 0.76542459 0.51222759]
  [0.20577984 0.14670165 0.5018223  0.18084043]
  [0.97212042 0.79956384 0.56755693 0.69581925]]

 [[0.98791492 0.23623783 0.794995   0.98038602]
  [0.42135554 0.5578607  0.11758058 0.41614577]
  [0.80336643 0.80246506 0.25273424 0.30283177]]]


In [121]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a[:2,1:3])

[[2 3]
 [6 7]]


In [122]:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


In [123]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a[[0, 1, 2], [0, 1, 0]])

[1 4 5]


In [125]:
a=np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)
b=np.array([1,2,1,0])
print(a[np.arange(4),b])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 2  6  8 10]


In [126]:
a[np.arange(4),b]+=10
print(a)

[[ 1 12  3]
 [ 4  5 16]
 [ 7 18  9]
 [20 11 12]]


In [129]:
a = np.array([[1,2], [3, 4], [5, 6]])
bool_idx = (a > 2)
print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [130]:
print(a[bool_idx])

[3 4 5 6]


In [131]:
print(a[a>2])

[3 4 5 6]


In [132]:
print(a[0].dtype)

int64


In [134]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(x+y)
print(np.add(x,y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [135]:
print(x-y)
print(np.subtract(x,y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [136]:
print(x*y)
print(np.multiply(x,y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [137]:
print(x/y)
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [138]:
print(np.sqrt(x+y))

[[2.44948974 2.82842712]
 [3.16227766 3.46410162]]


In [139]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

In [140]:
print(v.dot(w))

219


In [141]:
print(np.dot(v,w))

219


In [142]:
print(np.dot(x,v))

[29 67]


In [143]:
x = np.array([[1,2],[3,4]])


In [144]:
print(np.sum(x))

10


In [146]:
print(np.sum(x,axis=0))

[4 6]


In [147]:
print(np.sum(x,axis=1))


[3 7]


In [148]:
print(x)
print(x.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [149]:
v=np.array([x for x in range(1,4)])
print(v)
print(v.T)

[1 2 3]
[1 2 3]


In [150]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)

In [151]:
for i in range(4):
    y[i, :] = x[i, :] + v
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [155]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v,(4,1))
print(vv)
print(x+vv)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [162]:
!pip install imageio pillow

In [187]:
import imageio
import numpy as np
from PIL import Image
import requests
from io import BytesIO

# Load image from URL
url = "https://fastly.picsum.photos/id/237/536/354.jpg?hmac=i0yVXW1ORpyCZpQ-CknuyV-jbtU7_x9EBQVhvT5aRr0"
response = requests.get(url)
img = Image.open(BytesIO(response.content))
img=img.resize((200,200))
# Convert to numpy array
img = np.array(img)

print(img.dtype, img.shape)

uint8 (200, 200, 3)


In [188]:
img_tinted = img * [0.8,0.8,0.8]

In [189]:
img_tinted = np.clip(img_tinted, 0, 255)    # Ensure values in 0-255
img_tinted = img_tinted.astype(np.uint8)    # Convert back to uint8

In [190]:
Image.fromarray(img_tinted).save("resized_image.jpg")

In [191]:
import pandas as pd


In [192]:
s=pd.Series([1,3,5,np.nan,6,8])
print(s)

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64


In [193]:
dates=pd.date_range("20260101",periods=12)
dates

DatetimeIndex(['2026-01-01', '2026-01-02', '2026-01-03', '2026-01-04',
               '2026-01-05', '2026-01-06', '2026-01-07', '2026-01-08',
               '2026-01-09', '2026-01-10', '2026-01-11', '2026-01-12'],
              dtype='datetime64[ns]', freq='D')

In [195]:
df = pd.DataFrame(np.random.randn(12,4),index=dates,columns=list("ABCD"))
df

,A,B,C,D
2026-01-01,-0.212573,1.765467,0.089742,-0.247587
2026-01-02,-0.121589,-0.023518,0.394829,0.714547
2026-01-03,0.751007,-0.569489,0.905325,0.672081
2026-01-04,-0.442542,0.451438,0.741758,0.473355
2026-01-05,1.010988,0.520633,1.402231,-0.107157
2026-01-06,-0.585535,-0.053526,-1.696024,0.619597
2026-01-07,0.137180,1.512363,1.087411,-0.608448
2026-01-08,0.095382,0.456578,-0.348625,-0.309794
2026-01-09,-0.997167,0.935895,0.642432,0.872197
2026-01-10,0.715537,-1.523303,-1.844272,-1.540148
